version: "3"
services:
  nginx:
    build: ./src
    volumes:
     - '.:/app'
     - '/var/video-records:/usr/local/video-records'
    ports:
      - '8080:8080'
      - '1935:1935'
    tty: true
    stdin_open: true
  web:
    build: ./server
    ports: ['5000:5000']
    volumes: ['.:/app']
    tty: true
    stdin_open: true
